"""cria tabelas iniciais

Revision ID: 00820bbd5174
Revises: 
Create Date: 2026-07-03 23:53:35.024091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00820bbd5174'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('range_km', sa.Float(), nullable=False),
    sa.Column('max_passengers', sa.Integer(), nullable=False),
    sa.Column('max_payload_kg', sa.Float(), nullable=False),
    sa.Column('cruise_speed', sa.Float(), nullable=False),
    sa.Column('fuel_consumption', sa.Float(), nullable=False),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('runway_requirement', sa.Float(), nullable=False),
    sa.Column('operational_cost_hour', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircrafts_id'), 'aircrafts', ['id'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao', sa.String(), nullable=False),
    sa.Column('iata', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('runway_length', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_icao'), 'airports', ['icao'], unique=True)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_airport', sa.String(), nullable=False),
    sa.Column('destination_airport', sa.String(), nullable=False),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('cargo_weight', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_airport'], ['airports.icao'], ),
    sa.ForeignKeyConstraint(['origin_airport'], ['airports.icao'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('recommended_aircraft', sa.String(), nullable=False),
    sa.Column('llm_explanation', sa.String(), nullable=False),
    sa.Column('risk_analysis', sa.String(), nullable=True),
    sa.Column('operational_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_table('aircraft_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('range_score', sa.Float(), nullable=False),
    sa.Column('speed_score', sa.Float(), nullable=False),
    sa.Column('efficiency_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_scores_id'), 'aircraft_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircraft_scores_id'), table_name='aircraft_scores')
    op.drop_table('aircraft_scores')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_icao'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_aircrafts_id'), table_name='aircrafts')
    op.drop_table('aircrafts')
    # ### end Alembic commands ###
