"""adiciona campos de family, engine, mtow e afins

Revision ID: 21d8bfe14bb9
Revises: 00820bbd5174
Create Date: 2026-07-07 17:22:21.407226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d8bfe14bb9'
down_revision: Union[str, Sequence[str], None] = '00820bbd5174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('range_km', sa.Float(), nullable=True),
    sa.Column('max_passengers', sa.Integer(), nullable=True),
    sa.Column('max_payload_kg', sa.Float(), nullable=True),
    sa.Column('cruise_speed', sa.Float(), nullable=True),
    sa.Column('runway_requirement', sa.Float(), nullable=True),
    sa.Column('landing_weight_kg', sa.Float(), nullable=True),
    sa.Column('fuel_consumption', sa.Float(), nullable=True),
    sa.Column('mission_type', sa.String(), nullable=True),
    sa.Column('operational_cost_hour', sa.Float(), nullable=True),
    sa.Column('mtow_kg', sa.Float(), nullable=True),
    sa.Column('usable_fuel_kg', sa.Float(), nullable=True),
    sa.Column('service_ceiling_ft', sa.Integer(), nullable=True),
    sa.Column('engine_model', sa.String(), nullable=True),
    sa.Column('engines', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('aircraft_scores', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('aircraft_scores', sa.Column('estimated_flight_time', sa.Float(), nullable=True))
    op.add_column('aircraft_scores', sa.Column('weather_condition', sa.String(), nullable=True))
    op.add_column('aircraft_scores', sa.Column('required_runway', sa.Float(), nullable=True))
    op.add_column('aircraft_scores', sa.Column('cargo_volume', sa.Float(), nullable=True))
    op.add_column('aircraft_scores', sa.Column('budget', sa.Float(), nullable=True))
    op.drop_constraint(op.f('aircraft_scores_mission_id_fkey'), 'aircraft_scores', type_='foreignkey')
    op.drop_column('aircraft_scores', 'final_score')
    op.drop_column('aircraft_scores', 'efficiency_score')
    op.drop_column('aircraft_scores', 'mission_id')
    op.drop_column('aircraft_scores', 'aircraft_id')
    op.drop_column('aircraft_scores', 'speed_score')
    op.drop_column('aircraft_scores', 'cost_score')
    op.drop_column('aircraft_scores', 'range_score')
    op.add_column('missions', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('missions', sa.Column('estimated_flight_time', sa.Float(), nullable=True))
    op.add_column('missions', sa.Column('weather_condition', sa.String(), nullable=True))
    op.add_column('missions', sa.Column('required_runway', sa.Float(), nullable=True))
    op.add_column('missions', sa.Column('cargo_volume', sa.Float(), nullable=True))
    op.add_column('missions', sa.Column('budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'budget')
    op.drop_column('missions', 'cargo_volume')
    op.drop_column('missions', 'required_runway')
    op.drop_column('missions', 'weather_condition')
    op.drop_column('missions', 'estimated_flight_time')
    op.drop_column('missions', 'distance_km')
    op.add_column('aircraft_scores', sa.Column('range_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('cost_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('speed_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('aircraft_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('efficiency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('aircraft_scores', sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('aircraft_scores_mission_id_fkey'), 'aircraft_scores', 'missions', ['mission_id'], ['id'])
    op.drop_column('aircraft_scores', 'budget')
    op.drop_column('aircraft_scores', 'cargo_volume')
    op.drop_column('aircraft_scores', 'required_runway')
    op.drop_column('aircraft_scores', 'weather_condition')
    op.drop_column('aircraft_scores', 'estimated_flight_time')
    op.drop_column('aircraft_scores', 'distance_km')
    op.drop_table('aircrafts')
    # ### end Alembic commands ###
