"""adiciona campos de family, engine, mtow e afins

Revision ID: 8a276be31877
Revises: 21d8bfe14bb9
Create Date: 2026-07-07 17:28:09.395346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a276be31877'
down_revision: Union[str, Sequence[str], None] = '21d8bfe14bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
