"""adiciona mission_id e foreign keys em aircraft_scores

Revision ID: 9e4c3b338a0b
Revises: 8a276be31877
Create Date: 2026-07-14 23:08:07.000978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4c3b338a0b'
down_revision: Union[str, Sequence[str], None] = '8a276be31877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft_scores', sa.Column('mission_id', sa.Integer(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('aircraft_id', sa.Integer(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('cost_score', sa.Float(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('range_score', sa.Float(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('speed_score', sa.Float(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('capacity_score', sa.Float(), nullable=False))
    op.add_column('aircraft_scores', sa.Column('final_score', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'aircraft_scores', 'aircrafts', ['aircraft_id'], ['id'])
    op.create_foreign_key(None, 'aircraft_scores', 'missions', ['mission_id'], ['id'])
    op.drop_column('aircraft_scores', 'budget')
    op.drop_column('aircraft_scores', 'estimated_flight_time')
    op.drop_column('aircraft_scores', 'distance_km')
    op.drop_column('aircraft_scores', 'required_runway')
    op.drop_column('aircraft_scores', 'weather_condition')
    op.drop_column('aircraft_scores', 'cargo_volume')
    op.alter_column('airports', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airports', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airports', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('airports', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('airports', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('airports', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('missions', 'cargo_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('cargo_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('airports', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airports', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airports', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('airports', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('airports', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('airports', 'icao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('aircraft_scores', sa.Column('cargo_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft_scores', sa.Column('weather_condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('aircraft_scores', sa.Column('required_runway', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft_scores', sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft_scores', sa.Column('estimated_flight_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('aircraft_scores', sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'aircraft_scores', type_='foreignkey')
    op.drop_constraint(None, 'aircraft_scores', type_='foreignkey')
    op.drop_column('aircraft_scores', 'final_score')
    op.drop_column('aircraft_scores', 'capacity_score')
    op.drop_column('aircraft_scores', 'speed_score')
    op.drop_column('aircraft_scores', 'range_score')
    op.drop_column('aircraft_scores', 'cost_score')
    op.drop_column('aircraft_scores', 'aircraft_id')
    op.drop_column('aircraft_scores', 'mission_id')
    # ### end Alembic commands ###
