"""add nova_tabela

Revision ID: fd30e5e2b3c5
Revises: 9e4c3b338a0b
Create Date: 2026-07-16 22:31:05.018972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd30e5e2b3c5'
down_revision: Union[str, Sequence[str], None] = '9e4c3b338a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft_scores', sa.Column('weather_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft_scores', 'weather_score')
    # ### end Alembic commands ###
